//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S_Mod.data_access
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int review_id { get; set; }
        public int product_id { get; set; }
        public string customer_name { get; set; }
        public string customer_email { get; set; }
        public Nullable<int> rating { get; set; }
        public string comments { get; set; }
    }
}
